ignore:
  field_paths:
    - CreateUserInput.ServerId
    - CreateUserInput.UserName
    - CreateUserInput.Role
    - CreateUserInput.SshPublicKeyBody
    - CreateServerInput.EndpointDetails
    - CreateServerInput.Certificate
    - CreateServerInput.LoggingRole
  resource_names:
    - Access
    - Workflow
    - Agreement
    - Connector
    - Profile
resources:
  Server:
    exceptions:
      errors:
        404:
          code: ResourceNotFoundException
  User:
    fields:
      SshPublicKeys:
        is_read_only: true
        from:
          operation: DescribeUser
          path: User.SshPublicKeys
      ARN:
        is_read_only: true
        from:
          operation: DescribeUser
          path: User.Arn
    exceptions:
      errors:
        404:
          code: ResourceNotFoundException
